services:
  web:
    image: odoo:18.0
    working_dir: /opt/odoo
    depends_on:
      - db
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - config:/etc/odoo
      - extra-addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
  extra-addons:
  config: